# Generated by Django 4.0.5 on 2022-08-01 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('room', '0005_room_isprivate_room_usr1_room_usr2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='usr1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='home.account'),
        ),
        migrations.AlterField(
            model_name='room',
            name='usr2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='home.account'),
        ),
    ]
